export const acts = {
  START_LOADING_POSTS: 'START_LOADING_POSTS',
  END_LOADING_POSTS: 'END_LOADING_POSTS',
  START_LOADING_POST: 'START_LOADING_POST',
  END_LOADING_POST: 'END_LOADING_POST',
  FETCH_POSTS: 'FETCH_POSTS',
  FETCH_POST: 'FETCH_POST',
  ADD_POST: 'ADD_POST',
  DELETE_POST: 'DELETE_POST',
  UPDATE_POST: 'UPDATE_POST',
};
