export const acts = {
  START_LOADING: 'START_LOADING',
  END_LOADING: 'END_LOADING',
  FETCH_POSTS: 'FETCH_POSTS',
  FETCH_POST: 'FETCH_POST',
  ADD_POST: 'ADD_POST',
  DELETE_POST: 'DELETE_POST',
  UPDATE_POST: 'UPDATE_POST',
};
